### ISSUE TITLE
✨ Footer Styling

### ISSUE THREAD

**Issue by craineum** [CodingZeal/amaanytime#4]
## Story

**In order to protect our company**
**As a stakeholder**
**I need a footer that displays legal information**

## Acceptance Criteria

- The footer should have the following links: About, Contact, Privacy Policy, Terms & Conditions, Disclaimer
- Should also display copy right information
- Footer should work in all layouts starting with Mobile

## Design Implementation

[Link(s) to design](https://www.figma.com/file/71cvT12tjZmTiwg6nRyuJb/AMA-Anytime?node-id=204%3A5751&t=7t3buf69Rr6rc9ZH-1)

## Notes

Content and styling for all linked pages will come in future stories.

**Comment by archae0pteryx** [comment]
This happened during my login styling #12 There may need to be some tweaks.
- figma was copied ✅
- both mobile and desktop supported ✅
